### ISSUE TITLE
CMakeLists not working for latest minizip

### ISSUE THREAD

**Issue by binpick** [bjornblissing/osg-3rdparty-cmake#44]
The CMakeLists.txt points to 

SET(MINIZIP_SRCS
  ${MINIZIP_SOURCE_DIR}/crypt.c

that does not exist anymore in the current master branch.

**Comment by bjornblissing** [comment]
The Minizip project have performed some major refactoring.
The last working commit before this refactoring is nmoinvaz/minizip@dac37702b3fab4068ac9a7c4a992df7f0e4f14df

Since Minizip is only used in combination with Collada and Collada is not included with these dependencies I am considering dropping support for Minizip until Collada is included as well.

**Comment by bjornblissing** [comment]
I have updated the appveyor checkout hash. So the prebuilt version are now using the commit cited above.

The change can be found here:
3d09a87ce5f0ccfde0f8b3be28ec7a373b17da86
